In [11]:
import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

In [12]:
x = torch.tensor(1.,requires_grad=True)
w = torch.tensor(2.,requires_grad=True)
y = torch.tensor(3.,requires_grad=True)

In [13]:
y = w*x+b # y = 2 * x + 3

In [14]:
# 计算梯度
y.backward()

In [15]:
print(x.grad)

tensor(2.)


In [18]:
x = torch.randn(10, 3)
y = torch.randn(10, 2)

x

tensor([[-0.1389,  0.8733,  0.6584],
        [ 0.2254,  1.2349,  0.6699],
        [ 1.8278, -1.1462,  1.3215],
        [ 0.8102, -0.1563,  0.6842],
        [ 0.1212,  1.2317,  1.0636],
        [ 1.2146,  0.2205, -0.7026],
        [-1.3861,  0.2031, -0.0796],
        [ 0.2624, -0.6051,  1.2434],
        [ 0.6926, -0.7290, -0.5803],
        [-0.6504, -0.0220,  1.2404]])

In [19]:
# fully connected layer
liner = nn.Linear(3,2)
print(liner.weight)

Parameter containing:
tensor([[-0.0232, -0.1087, -0.1980],
        [-0.4687,  0.1911,  0.4329]], requires_grad=True)


In [20]:
# loss function and optimizer

criterion = nn.MSELoss()
optimizer = torch.optim.SGD(liner.parameters(),lr=0.01)

In [22]:
# 预测
pre = liner(x)
print(pre)

tensor([[-0.2332,  0.7722],
        [-0.2832,  0.6755],
        [-0.1906, -0.2484],
        [-0.1484,  0.1418],
        [-0.3584,  0.8942],
        [ 0.0759, -0.5761],
        [ 0.0148,  0.9092],
        [-0.1976,  0.5548],
        [ 0.1670, -0.4599],
        [-0.2393,  1.0928]], grad_fn=<AddmmBackward0>)


In [25]:
loss = criterion(pre, y)
print('loss: ', loss.item())

loss:  2.4043431282043457


In [26]:
loss.backward()

In [28]:
# Print out the gradients.
print ('dL/dw: ', liner.weight.grad) 
print ('dL/db: ', liner.bias.grad)

dL/dw:  tensor([[-0.7847,  0.5766, -0.3552],
        [-0.3599,  0.7962,  0.9207]])
dL/db:  tensor([-0.3649,  0.7189])


In [29]:
# 梯度下降
optimizer.step()

In [31]:
# 反向传播，优化后的loss
pred = liner(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

loss after 1 step optimization:  2.37119197845459


https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/01-basics/pytorch_basics/main.py